// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240304092949_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entity.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProductBrandId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductTypeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductBrandId");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("838c781f-6650-44fb-a84f-8cbac2047363"),
                            Description = "Description 1",
                            Name = "Product 1",
                            Price = 10.99m,
                            ProductBrandId = new Guid("794a5bf3-db1f-4d4a-86e7-1021dbb8f667"),
                            ProductTypeId = new Guid("dc1cc068-6c14-4cb2-9b3d-858953d41e59")
                        },
                        new
                        {
                            Id = new Guid("63cd83fb-da73-4880-b90f-2ba32d24ab04"),
                            Description = "Описание продукта 2",
                            Name = "Product 2",
                            Price = 20.99m,
                            ProductBrandId = new Guid("794a5bf3-db1f-4d4a-86e7-1021dbb8f667"),
                            ProductTypeId = new Guid("dc1cc068-6c14-4cb2-9b3d-858953d41e59")
                        },
                        new
                        {
                            Id = new Guid("8789b1be-f690-41a0-808e-95b09f74e3c7"),
                            Description = "Description 3",
                            Name = "Product 3",
                            Price = 15.49m,
                            ProductBrandId = new Guid("5f71a742-c0ab-4a86-8754-8328ef4f37f4"),
                            ProductTypeId = new Guid("dc1cc068-6c14-4cb2-9b3d-858953d41e59")
                        },
                        new
                        {
                            Id = new Guid("e64b9097-62a0-40cd-bebd-6b677419d577"),
                            Description = "Description 4",
                            Name = "Product 4",
                            Price = 30.99m,
                            ProductBrandId = new Guid("5f71a742-c0ab-4a86-8754-8328ef4f37f4"),
                            ProductTypeId = new Guid("e29b5399-d2d0-4889-bdbc-1a74b2f06aaf")
                        },
                        new
                        {
                            Id = new Guid("c4d5984c-2d8d-4a75-b38a-635beaa30517"),
                            Description = "Description 5",
                            Name = "Product 5",
                            Price = 25.99m,
                            ProductBrandId = new Guid("9b8544ac-99fb-4201-acd4-b6c25c9c1918"),
                            ProductTypeId = new Guid("dc1cc068-6c14-4cb2-9b3d-858953d41e59")
                        },
                        new
                        {
                            Id = new Guid("24afe402-5f06-482f-920b-f9533f069052"),
                            Description = "Description 6",
                            Name = "Product 6",
                            Price = 18.99m,
                            ProductBrandId = new Guid("9b8544ac-99fb-4201-acd4-b6c25c9c1918"),
                            ProductTypeId = new Guid("e29b5399-d2d0-4889-bdbc-1a74b2f06aaf")
                        },
                        new
                        {
                            Id = new Guid("a01420ff-9e62-41cd-8513-3ffcb76f6c66"),
                            Description = "Description 7",
                            Name = "Product 7",
                            Price = 22.49m,
                            ProductBrandId = new Guid("9b8544ac-99fb-4201-acd4-b6c25c9c1918"),
                            ProductTypeId = new Guid("690a87fe-1e04-470a-a11b-50807f73f5ba")
                        },
                        new
                        {
                            Id = new Guid("970ee704-1d3c-457e-aa47-d70b1529868f"),
                            Description = "Description 8",
                            Name = "Product 8",
                            Price = 12.99m,
                            ProductBrandId = new Guid("9b8544ac-99fb-4201-acd4-b6c25c9c1918"),
                            ProductTypeId = new Guid("690a87fe-1e04-470a-a11b-50807f73f5ba")
                        },
                        new
                        {
                            Id = new Guid("cf2d4065-81a6-48fe-9b8b-0c6ae56c2b80"),
                            Description = "Description 9",
                            Name = "Product 9",
                            Price = 28.99m,
                            ProductBrandId = new Guid("5f71a742-c0ab-4a86-8754-8328ef4f37f4"),
                            ProductTypeId = new Guid("690a87fe-1e04-470a-a11b-50807f73f5ba")
                        },
                        new
                        {
                            Id = new Guid("271b2797-251f-42ba-8465-035bcb7353ce"),
                            Description = "Description 10",
                            Name = "Product 10",
                            Price = 35.99m,
                            ProductBrandId = new Guid("5f71a742-c0ab-4a86-8754-8328ef4f37f4"),
                            ProductTypeId = new Guid("e29b5399-d2d0-4889-bdbc-1a74b2f06aaf")
                        });
                });

            modelBuilder.Entity("Domain.Entity.ProductBrand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProductBrands");

                    b.HasData(
                        new
                        {
                            Id = new Guid("794a5bf3-db1f-4d4a-86e7-1021dbb8f667"),
                            Name = "Brand 1"
                        },
                        new
                        {
                            Id = new Guid("5f71a742-c0ab-4a86-8754-8328ef4f37f4"),
                            Name = "Brand 2"
                        },
                        new
                        {
                            Id = new Guid("9b8544ac-99fb-4201-acd4-b6c25c9c1918"),
                            Name = "Brand 3"
                        });
                });

            modelBuilder.Entity("Domain.Entity.ProductType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProductTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dc1cc068-6c14-4cb2-9b3d-858953d41e59"),
                            Name = "Type 1"
                        },
                        new
                        {
                            Id = new Guid("e29b5399-d2d0-4889-bdbc-1a74b2f06aaf"),
                            Name = "Type 2"
                        },
                        new
                        {
                            Id = new Guid("690a87fe-1e04-470a-a11b-50807f73f5ba"),
                            Name = "Type 3"
                        });
                });

            modelBuilder.Entity("Domain.Entity.Product", b =>
                {
                    b.HasOne("Domain.Entity.ProductBrand", "ProductBrand")
                        .WithMany()
                        .HasForeignKey("ProductBrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entity.ProductType", "ProductType")
                        .WithMany()
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductBrand");

                    b.Navigation("ProductType");
                });
#pragma warning restore 612, 618
        }
    }
}
